###
GET http://localhost:8080/api/hello

###
GET http://localhost:8080/api/articles/{{id}}

###
POST http://localhost:8080/api/articles

###
PATCH http://localhost:8080/api/articles/{{id}}


###
DELETE http://localhost:8080/api/articles/{{id}}