###
GET http://localhost:8080/api/articles/{{articleId}}/comments

###

###
POST http://localhost:8080/api/articles/{{pathId}}/comments
Content-Type: application/json

{
  "id": null,
  "article_id": 4,
  "nicknmae": "Kknd",
  "body": "Kknd야"
}